import axios from "axios";
import { useState } from "react";

export default function CreateNotification() {
    let [userId, setUserId] = useState("");
    let [message, setMessage] = useState("");
    let [category, setCategory] = useState("");
    let [status, setStatus] = useState("");
    let [createdDate, setCreatedDate] = useState("");
    let [readFlag, setReadFlag] = useState(false);  // ✅ boolean, matches entity

    let userIdHandler = (event) => setUserId(event.target.value);
    let messageHandler = (event) => setMessage(event.target.value);
    let categoryHandler = (event) => setCategory(event.target.value);
    let statusHandler = (event) => setStatus(event.target.value);
    let createdDateHandler = (event) => setCreatedDate(event.target.value);
    let readFlagHandler = (event) => setReadFlag(event.target.checked); // ✅ checkbox gives true/false

    let saveHandler = () => {
        let url = "http://localhost:9011/api/addNotification";
        let data = {
            "notification": {
                // ✅ notificationId removed — auto-generated by DB
                "userId": parseInt(userId),
                "message": message,
                "category": category,
                "status": status,
                "createdDate": createdDate + "T00:00:00",  // ✅ LocalDateTime format
                "readFlag": readFlag                        // ✅ matches entity field name
            }
        };
        axios.post(url, data)
            .then((response) => {
                alert("Notification added successfully!");
            })
            .catch((err) => {
                alert("Error: " + err.message);
            });
    }

    return (
        <div>
            <label>User ID</label>
            <input value={userId} onChange={userIdHandler} type="number" />
            <br />

            <label>Message</label>
            <input value={message} onChange={messageHandler} />
            <br />

            <label>Category</label>
            <input value={category} onChange={categoryHandler} />
            <br />

            <label>Status</label>
            <input value={status} onChange={statusHandler} />
            <br />

            <label>Created Date</label>
            <input type="date" value={createdDate} onChange={createdDateHandler} />
            {/* ✅ type="date" gives yyyy-MM-dd, we append T00:00:00 for LocalDateTime */}
            <br />

            <label>Read Flag</label>
            <input type="checkbox" checked={readFlag} onChange={readFlagHandler} />
            {/* ✅ checkbox gives boolean true/false directly */}
            <br />

            <button onClick={saveHandler}>SAVE</button>
        </div>
    );
}